---
title: " "
output: pdf_document
header-includes:
  - \usepackage{float}
  - \usepackage{sectsty}
---

# Introduction

- introduce the reader to the subject area and clarify the knowledge gap that the dissertation research will fill.
- set the context for the dissertation by reviewing the relevant literature.
- include relevant references to general (theoretical papers and reviews) and specific (specific to the particular question addressed) literature, to justify the research that has been undertaken and define the questions being addressed.
- state the primary research questions and hypotheses in the final paragraph.
- follow an ‘inverted triangle’ format, progressing from general scientific ideas and why they matter to the specific research questions addressed in the dissertation project. 

*The introduction should not be just a ‘Literature Review’.*

## Research Questions

**1. Is there a strong degree of overlap between bottom-up and top-down mean and uncertainty SLA estimates, and is it constant at differing spatial extents?**

H0. There is no strong degree of overlap, nor at differing spatial extents;

H1. The degree of overlap is strong at varying spatial extents;

H2. The degree of overlap varies with spatial extents.

**2. Is there a difference in degree of overlap for SLA mean and uncertainty estimates, among biomes with differing leaf seasonalities (i.e. deciduous versus evergreen)? / Do continent-specific characteristics affect the degree of overlap among biomes?**

H0. There is no difference in degree of overlap among biomes with differing leaf seasonalities;

H1. There is a high difference in degree of overlap among biomes with differing leaf seasonalities;

H2. The difference in overlap varies with specific biomes. 

**3. Do the two SLA mean and uncertainty estimates have similar sensitivities to climate data, i.e. mean global precipitation and mean temperature?**

H0. The SLA estimates have no similar sensitivities to climate data;

H1. The SLA estimates have highly similar sensitivities to climate data; 

H2. The SLA estimates have low similarity in sensitivity to climate data. 



